# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MARC-Fast
version:      0.03
version_from: Fast.pm
installdirs:  site
requires:
    Carp:                          0
    Test::Exception:               0
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
